# TODO: SVG images
# TODO: Dark mode
# TODO: Fix PDF cover size mismatch

BOOK_FILE="washing-code"
BOOK_TITLE="Washing your code: clean code for frontend developers"
CHAPTERS_FILES="generator/settings.md generator/content/*.md"
# TODO: Add the rest of the chapters
COVER="manuscript/resources/images/cover.jpg"
VERSION="$(date "+%B %e, %Y")"
DIST_DIR=dist

mkdir -p "$DIST_DIR"

# Generate PDF
echo
echo "[BUILD] Generate PDF ebook..."

pandoc $CHAPTERS_FILES \
  --resource-path="manuscript/resources" \
  --output="$DIST_DIR/$BOOK_FILE-content.pdf" \
  --top-level-division=chapter \
  --table-of-contents --toc-depth=2 \
  --template="generator/eisvogel.latex" \
  --highlight-style "generator/theme.theme" \
  --lua-filter "generator/filters/tips.lua" \
  -f commonmark_x \
  -M date="$VERSION"

# Attach the cover
pdfunite "generator/cover.pdf" "$DIST_DIR/$BOOK_FILE-content.pdf" "$DIST_DIR/$BOOK_FILE.pdf"

# Remove the temporary file generated by Pandoc
rm "$DIST_DIR/$BOOK_FILE-content.pdf"

# Generate Epub
echo
echo "[BUILD] Generate Epub ebook..."

pandoc $CHAPTERS_FILES \
  --resource-path="manuscript/resources" \
  --output="$DIST_DIR/$BOOK_FILE.epub" \
  --top-level-division=chapter \
  --table-of-contents --toc-depth=2 \
  --standalone \
  --epub-cover-image="$COVER" \
  --highlight-style "generator/theme.theme" \
  --css "generator/epub.css" \
  -f commonmark_x \
  -M date="$VERSION"

echo
echo "[BUILD] 🦆 Done"
echo
