# TODO: Make table headers bold
# TODO: Size individual illustrations
# TODO: Correct diff syntax highlighting colors

BOOK_FILE="washing-code"
BOOK_TITLE="Washing your code: clean code for frontend developers"
CHAPTERS_FILES_EPUB="generator/settings.md generator/content-epub/*.md"
CHAPTERS_FILES_PDF="generator/settings.md generator/content-pdf/*.md"
SOURCE_FORMAT="commonmark_x+implicit_figures"
VERSION="$(date "+%B %e, %Y")"

mkdir -p "dist"

# Generate PDF
echo
echo "[BUILD] Generate PDF ebook..."

# Available PDF engines:
# - pdflatex: default
# - lualatex: doesn't support \DeclareUnicodeCharacter, broken fonts
# - xelatex: doesn't support \DeclareUnicodeCharacter, broken fonts

pandoc $CHAPTERS_FILES_PDF \
  --resource-path="manuscript/resources" \
  --output="dist/$BOOK_FILE-content.pdf" \
  --pdf-engine=pdflatex \
  --top-level-division=chapter \
  --table-of-contents --toc-depth=2 \
  --template="generator/eisvogel.latex" \
  --highlight-style "generator/theme.theme" \
  --lua-filter "generator/filters/tips.lua" \
  --from "$SOURCE_FORMAT" \
  -M date="$VERSION"

# Attach the cover
pdfunite "media/cover.pdf" "dist/$BOOK_FILE-content.pdf" "dist/$BOOK_FILE.pdf"

# Remove the temporary file generated by Pandoc
rm "dist/$BOOK_FILE-content.pdf"

# Generate Epub
echo
echo "[BUILD] Generate Epub ebook..."

pandoc $CHAPTERS_FILES_EPUB \
  --resource-path="manuscript/resources" \
  --output="dist/$BOOK_FILE.epub" \
  --top-level-division=chapter \
  --table-of-contents --toc-depth=2 \
  --standalone \
  --epub-cover-image="media/cover.jpg" \
  --highlight-style "generator/theme.theme" \
  --css "generator/epub.css" \
  --from "$SOURCE_FORMAT" \
  -M date="$VERSION"

echo
echo "[BUILD] 🦆 Done"
echo
